name: Triggers
on: 
  # if someone opens PR to main branch
  pull_request:
    types: [opened, reopened]
    branches:
      - 'releases/**'
  # push:
  #   branches:
  #     - 'main'
  # workflow_dispatch
  # [push] # Triggers the workflow on every push to the repository


jobs:
  # Job name
  trigger:
    runs-on: ubuntu-latest # Github hosted runners
    steps:
      # - name: Manual dispatch
      #   run: echo "manually dispatched" # The command to execute
      - name: feature branch push
        run: echo "main branch push"
      