name: Triggers
on: workflow_dispatch
  

jobs:
  # Job name
  trigger:
    runs-on: ubuntu-latest # Github hosted runners
    steps:
      - name: Manual dispatch
        run: echo "manually dispatched" # The command to execute
      