name: Triggers
on: 
  push:
   branches:
      - 'feature*'
  # workflow_dispatch
  # [push] # Triggers the workflow on every push to the repository
  

jobs:
  # Job name
  trigger:
    runs-on: ubuntu-latest # Github hosted runners
    steps:
      #- name: Manual dispatch
      # run: echo "manually dispatched" # The command to execute
      - name: feature branch push
        run: echo "main branch push"
      